### PR TITLE
Fixed map function call that causes problems in Grafana 10 (bump to 1.1.1)

### PR DESCRIPTION
**Pull request by Sawy7**
I changed one line in dataParser.ts so that this panel plugin now works in the latest version. I verified on my local instance that it didn't work before and now works just fine. Also bumped the minor version to 1.1.1. Don't know if that is desirable.

This fixes issue #18 

Thanks for your work on this amazing plugin!

### CODE REVIEW

**Comment by aned** [comment]
@KatrinaTurner can this be reviewed please?

**Comment by KatrinaTurner** [comment]
Thank you for the PR!  Taking a look!

**Comment by KatrinaTurner** [comment]
Hi @Sawy7 ! Can you actually change this to request it is merged into 1.1.1 branch instead of master please?  I just created it for you :) After that I can approve, merge and re-release

**Comment by Sawy7** [comment]
Hey @KatrinaTurner, I just changed the destination branch to 1.1.1. Thanks for your time!

**Review by KatrinaTurner — APPROVED** [review]

**Comment by AbrahamPrez25** [comment]
Thank you both for this fix. When will it be available in the master branch? @KatrinaTurner

**Comment by KatrinaTurner** [comment]
I usually wait until Grafana accepts the update, but since it's so simple I can merge now :)

**Comment by AbrahamPrez25** [comment]
I saw you already did! Thank you! I asked because I thought that it would automatically show up in Grafana this new version. But I guess it won't happen until they accept the update. How long does this usually take? The only way to check it is to look at the site https://grafana.com/grafana/plugins/netsage-sankey-panel/ ? Thanks in advance, I am a bit new to this "plugin development" face of Grafana, your work helps a lot, Katrina :heart:

**Comment by KatrinaTurner** [comment]
Yes, we have to wait for them to push the change to the library. I know
they are a bit backed up right now so not sure how long it will take.
Hopefully not longer than a couple weeks.
You can check the plugin on Grafana or if you're part of the Grafana
community slack, they have a #plugins channel where they post new plugin
publications & updates.

**Comment by KatrinaTurner** [comment]
Hah! Actually it looks like it just got published! You should be able to
just click update on the plugin in your Grafana instance and it should go
through 🙂

**Pull request merged**
